# Generated by Django 4.2.7 on 2026-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event'], name='ticket_type_event_i_802d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['ticket_type'], name='ticket_type_ticket__159983_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['is_active'], name='ticket_type_is_acti_9178fb_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['sale_start'], name='ticket_type_sale_st_c08779_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['sale_end'], name='ticket_type_sale_en_101278_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'is_active'], name='ticket_type_event_i_c71083_idx'),
        ),
    ]
