# Generated by Django 4.2.7 on 2026-03-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickettype_ticket_type_event_i_802d9e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['-created_at']},
        ),
    ]
