# Generated by Django 4.2.7 on 2026-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['is_used'], name='qrcodes_is_used_49d672_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['used_by'], name='qrcodes_used_by_672a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['created_at'], name='qrcodes_created_40a071_idx'),
        ),
    ]
